name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: asdf_install
        uses: asdf-vm/actions/install@v1

      - name: install cdktf
        run: npm install -g cdktf-cli

      - name: Build
        run: make get tools test
